import type { Phase } from "@/types/roadmap";

export const phases: Phase[] = [
  {
    id: "phase-1",
    number: 1,
    title: "Foundation & Solidification",
    subtitle: "Solidify fundamentals, TypeScript, clean architecture",
    weeks: "Weeks 1–4",
    sections: [
      {
        id: "p1-typescript",
        title: "TypeScript for Backend Engineers",
        topics: [
          { id: "p1-ts-strict", label: "Strict mode configuration", subtopics: ["noImplicitAny", "strictNullChecks", "strictFunctionTypes"] },
          { id: "p1-ts-utility", label: "Utility types (Partial, Pick, Omit, Record)", subtopics: ["Partial<T>", "Pick<T,K>", "Omit<T,K>", "Record<K,T>"] },
          { id: "p1-ts-generics", label: "Generic functions and constraints", subtopics: ["Type parameters", "Generic constraints", "Conditional types"] },
          { id: "p1-ts-discriminated", label: "Discriminated unions", subtopics: ["Tagged unions", "Exhaustive type checking"] },
          { id: "p1-ts-module", label: "Module resolution", subtopics: ["ES modules vs CommonJS", "Path aliases", "Barrel exports"] },
        ],
      },
      {
        id: "p1-nodejs",
        title: "Node.js Runtime Internals",
        topics: [
          { id: "p1-node-event-loop", label: "Event loop phases", subtopics: ["timers", "poll", "check", "close callbacks"] },
          { id: "p1-node-libuv", label: "libuv thread pool", subtopics: ["Default thread pool size", "File I/O operations", "DNS lookups"] },
          { id: "p1-node-micro-macro", label: "Microtask queue vs macrotask queue", subtopics: ["process.nextTick", "Promise callbacks", "setTimeout/setImmediate"] },
          { id: "p1-node-blocking", label: "Blocking vs non-blocking I/O", subtopics: ["Synchronous operation impact", "Event loop stall detection"] },
        ],
      },
      {
        id: "p1-http",
        title: "HTTP Deep Dive",
        topics: [
          { id: "p1-http-handshake", label: "TCP handshake" },
          { id: "p1-http-versions", label: "HTTP/1.1 vs HTTP/2" },
          { id: "p1-http-keepalive", label: "Connection keep-alive" },
          { id: "p1-http-headers", label: "Headers and caching semantics" },
          { id: "p1-http-status", label: "Status codes semantics" },
          { id: "p1-http-idempotency", label: "Idempotency and safe methods" },
        ],
      },
      {
        id: "p1-express",
        title: "Express.js Architecture Patterns",
        topics: [
          { id: "p1-exp-middleware", label: "Middleware pipeline", subtopics: ["Application-level middleware", "Router-level middleware", "Error-handling middleware"] },
          { id: "p1-exp-error", label: "Error-handling middleware" },
          { id: "p1-exp-modularity", label: "Route modularity" },
          { id: "p1-exp-lifecycle", label: "req/res lifecycle" },
        ],
      },
      {
        id: "p1-clean-arch",
        title: "Clean Architecture for Node.js",
        topics: [
          { id: "p1-ca-controllers", label: "Controllers (HTTP layer)" },
          { id: "p1-ca-services", label: "Services (business logic)" },
          { id: "p1-ca-repos", label: "Repositories (data access)" },
          { id: "p1-ca-di", label: "Dependency inversion principle" },
          { id: "p1-ca-mixing", label: "Why mixing layers creates unmaintainable codebases" },
        ],
      },
      {
        id: "p1-postgres",
        title: "PostgreSQL Fundamentals (Deep)",
        topics: [
          { id: "p1-pg-acid", label: "ACID properties with real examples" },
          { id: "p1-pg-isolation", label: "Transaction isolation levels", subtopics: ["Read committed", "Repeatable read", "Serializable"] },
          { id: "p1-pg-indexes", label: "Indexes (B-Tree, Hash, partial indexes)" },
          { id: "p1-pg-explain", label: "EXPLAIN ANALYZE" },
          { id: "p1-pg-nplus1", label: "N+1 query detection" },
        ],
      },
      {
        id: "p1-prisma",
        title: "Prisma ORM Mastery",
        topics: [
          { id: "p1-prisma-schema", label: "Schema design" },
          { id: "p1-prisma-migrations", label: "Migrations workflow" },
          { id: "p1-prisma-transactions", label: "Transactions" },
          { id: "p1-prisma-raw", label: "Raw queries when Prisma is not enough" },
          { id: "p1-prisma-pooling", label: "Connection pooling" },
          { id: "p1-prisma-optimization", label: "Query optimization with select/include" },
        ],
      },
      {
        id: "p1-auth",
        title: "Authentication & Authorization Patterns",
        topics: [
          { id: "p1-auth-jwt", label: "JWT deep dive (header/payload/signature)" },
          { id: "p1-auth-refresh", label: "Refresh token rotation" },
          { id: "p1-auth-revocation", label: "Token revocation strategies" },
          { id: "p1-auth-bcrypt", label: "bcrypt cost factor" },
          { id: "p1-auth-session-vs-jwt", label: "Session vs JWT tradeoffs" },
          { id: "p1-auth-rbac", label: "RBAC implementation" },
          { id: "p1-auth-oauth", label: "OAuth 2.0 flow (conceptual)" },
        ],
      },
      {
        id: "p1-zod",
        title: "Input Validation & Zod",
        topics: [
          { id: "p1-zod-runtime", label: "Runtime type-safety" },
          { id: "p1-zod-schema", label: "Schema-first validation" },
          { id: "p1-zod-custom", label: "Custom validators" },
          { id: "p1-zod-transforms", label: "Transformations" },
          { id: "p1-zod-malicious", label: "Treat all external input as malicious" },
        ],
      },
      {
        id: "p1-config",
        title: "Environment Configuration",
        topics: [
          { id: "p1-config-dotenv", label: ".env patterns" },
          { id: "p1-config-validation", label: "Config validation at startup (fail fast)" },
          { id: "p1-config-secrets", label: "Secrets management principles" },
          { id: "p1-config-commit", label: "Never commit secrets" },
          { id: "p1-config-12factor", label: "12-Factor App config principle" },
        ],
      },
    ],
    projects: [
      {
        id: "p1-proj-auth",
        title: "Project 1A — Production Auth API",
        description: "Complete authentication service with refresh tokens, RBAC, and rate limiting",
        requirements: [
          "User registration with email verification flow",
          "Login with access token (15 min) + refresh token (7 days) rotation",
          "Role-Based Access Control: admin, editor, viewer roles",
          "Password reset via time-limited signed tokens",
          "Rate limiting on auth endpoints",
          "Soft-delete users, audit log of all auth events",
          "Full TypeScript, strict mode, no any types",
        ],
      },
      {
        id: "p1-proj-blog",
        title: "Project 1B — Blog Platform REST API",
        description: "Multi-author CMS backend with complex querying and full pagination",
        requirements: [
          "Posts with tags, categories, and authors",
          "Cursor-based pagination",
          "Full-text search using PostgreSQL tsvector",
          "Draft / Published / Archived post states",
          "Comment system with nested replies",
          "Image metadata storage",
          "API versioning via URL prefix: /api/v1/",
        ],
      },
    ],
    checkpoint: [
      "Explain the difference between authentication and authorization",
      "A user reports login is slow — identify three possible causes",
      "Why is OFFSET pagination dangerous on a table with 10 million rows?",
      "You deploy to two server instances — the rate limiter breaks. Why?",
      "What is the N+1 query problem? Show an example from Prisma.",
    ],
  },
  {
    id: "phase-2",
    number: 2,
    title: "Intermediate: Performance & Reliability",
    subtitle: "Caching, queues, DB optimization, testing",
    weeks: "Weeks 5–10",
    sections: [
      {
        id: "p2-redis",
        title: "Redis — Complete Mental Model",
        topics: [
          { id: "p2-redis-ds", label: "Data structures (String, Hash, List, Set, Sorted Set, Stream)" },
          { id: "p2-redis-ttl", label: "TTL and expiration" },
          { id: "p2-redis-eviction", label: "Eviction policies (LRU, LFU, allkeys vs volatile)" },
          { id: "p2-redis-atomic", label: "Atomic operations" },
          { id: "p2-redis-lua", label: "Lua scripting for complex operations" },
        ],
      },
      {
        id: "p2-caching",
        title: "Caching Strategies",
        topics: [
          { id: "p2-cache-aside", label: "Cache-aside (lazy loading)" },
          { id: "p2-cache-write-through", label: "Write-through" },
          { id: "p2-cache-write-behind", label: "Write-behind" },
          { id: "p2-cache-stampede", label: "Cache stampede prevention" },
          { id: "p2-cache-invalidation", label: "Cache invalidation strategies" },
          { id: "p2-cache-when-not", label: "When NOT to cache" },
        ],
      },
      {
        id: "p2-redis-sessions",
        title: "Redis for Sessions & Rate Limiting",
        topics: [
          { id: "p2-redis-ratelimit", label: "Distributed rate limiting (sliding window)" },
          { id: "p2-redis-locks", label: "Distributed locks with SET NX EX" },
          { id: "p2-redis-sessions-store", label: "Session storage patterns" },
          { id: "p2-redis-jwt-blacklist", label: "Token blacklisting for JWT revocation" },
        ],
      },
      {
        id: "p2-db-perf",
        title: "Database Performance & Query Optimization",
        topics: [
          { id: "p2-db-explain", label: "EXPLAIN ANALYZE output interpretation" },
          { id: "p2-db-index-types", label: "Index types (B-Tree, GIN, BRIN)" },
          { id: "p2-db-composite", label: "Composite indexes and column order" },
          { id: "p2-db-covering", label: "Covering indexes" },
          { id: "p2-db-partial", label: "Partial indexes" },
          { id: "p2-db-pooling", label: "Connection pool sizing (PgBouncer)" },
          { id: "p2-db-vacuum", label: "VACUUM and autovacuum" },
        ],
      },
      {
        id: "p2-migrations",
        title: "Database Migrations in Production",
        topics: [
          { id: "p2-mig-expand-contract", label: "Expand-contract migration pattern" },
          { id: "p2-mig-nullable", label: "Adding nullable columns first" },
          { id: "p2-mig-backfill", label: "Backfilling data" },
          { id: "p2-mig-rename", label: "Rename via dual-write" },
          { id: "p2-mig-zero-downtime", label: "Zero-downtime migration principles" },
        ],
      },
      {
        id: "p2-files",
        title: "File Upload Architecture",
        topics: [
          { id: "p2-files-not-db", label: "Why never store files in DB or app server" },
          { id: "p2-files-s3", label: "S3-compatible storage (MinIO locally)" },
          { id: "p2-files-presigned", label: "Presigned URLs for direct client uploads" },
          { id: "p2-files-multipart", label: "Multipart upload for large files" },
          { id: "p2-files-queues", label: "Post-processing with queues" },
          { id: "p2-files-virus", label: "Virus scanning hooks" },
        ],
      },
      {
        id: "p2-bullmq",
        title: "Background Jobs & Worker Queues (BullMQ)",
        topics: [
          { id: "p2-bull-producer-consumer", label: "Producer-consumer pattern" },
          { id: "p2-bull-priorities", label: "Job priorities" },
          { id: "p2-bull-retry", label: "Retry strategies with exponential backoff" },
          { id: "p2-bull-dlq", label: "Dead letter queues" },
          { id: "p2-bull-concurrency", label: "Concurrency control" },
          { id: "p2-bull-dedup", label: "Job deduplication" },
          { id: "p2-bull-delayed", label: "Delayed jobs" },
        ],
      },
      {
        id: "p2-testing",
        title: "Testing Backend Systems",
        topics: [
          { id: "p2-test-pyramid", label: "Unit vs integration vs E2E (testing pyramid)" },
          { id: "p2-test-mocking", label: "Mocking vs stubbing" },
          { id: "p2-test-db", label: "Testing with a real database" },
          { id: "p2-test-supertest", label: "Supertest for HTTP testing" },
          { id: "p2-test-what", label: "What to test vs what not to test" },
          { id: "p2-test-coverage", label: "Test coverage as signal, not goal" },
        ],
      },
      {
        id: "p2-api-design",
        title: "API Design Best Practices",
        topics: [
          { id: "p2-api-rest", label: "RESTful resource naming" },
          { id: "p2-api-methods", label: "HTTP method semantics" },
          { id: "p2-api-idempotency", label: "Idempotency keys for POST" },
          { id: "p2-api-pagination", label: "Pagination standards (cursor vs offset)" },
          { id: "p2-api-filtering", label: "Filtering and sorting patterns" },
          { id: "p2-api-versioning", label: "API versioning strategies" },
          { id: "p2-api-errors", label: "Consistent error envelopes" },
        ],
      },
      {
        id: "p2-logging",
        title: "Structured Logging",
        topics: [
          { id: "p2-log-console", label: "Why console.log kills production debugging" },
          { id: "p2-log-winston-pino", label: "Winston/Pino structured logging" },
          { id: "p2-log-levels", label: "Log levels and when to use them" },
          { id: "p2-log-correlation", label: "Correlation IDs for request tracing" },
          { id: "p2-log-aggregation", label: "Log aggregation concepts" },
          { id: "p2-log-pii", label: "What to log and what never to log" },
        ],
      },
    ],
    projects: [
      {
        id: "p2-proj-upload",
        title: "Project 2A — File Upload & Processing Service",
        description: "Async media processing pipeline with job queues, presigned URLs, and status tracking",
        requirements: [
          "Accept image and PDF uploads up to 50MB via presigned S3 URLs",
          "Image resizing job: generate 3 thumbnail sizes asynchronously",
          "PDF text extraction job",
          "Job status tracking: pending, processing, done, failed",
          "Retry failed jobs up to 3 times with exponential backoff",
          "Webhook notification to caller when processing completes",
          "Rate limit upload endpoints per user",
        ],
      },
      {
        id: "p2-proj-ecommerce",
        title: "Project 2B — E-Commerce Backend",
        description: "Inventory, orders, and payments with distributed consistency guarantees",
        requirements: [
          "Product catalog with inventory tracking (prevent oversell)",
          "Shopping cart backed by Redis (TTL-based expiration)",
          "Order placement with inventory reservation pattern",
          "Payment intent creation (Stripe-compatible flow, mock)",
          "Order state machine: pending → reserved → paid → shipped → delivered",
          "Email notifications via job queue on order state changes",
          "Admin dashboard endpoints with reporting queries",
        ],
      },
    ],
    checkpoint: [
      "Explain cache stampede and how to prevent it with 10,000 concurrent users",
      "Your BullMQ worker crashes mid-job — what happens?",
      "You add an index but the query is still slow — what three things do you check?",
      "Describe the expand-contract migration pattern. When is it necessary?",
      "What's the difference between a unit test and an integration test for a REST API?",
    ],
  },
  {
    id: "phase-3",
    number: 3,
    title: "Advanced: Distributed Systems & Event-Driven Architecture",
    subtitle: "Event-driven systems, distributed patterns",
    weeks: "Weeks 11–15",
    sections: [
      {
        id: "p3-distributed-fundamentals",
        title: "Distributed Systems Fundamentals",
        topics: [
          { id: "p3-dist-cap", label: "CAP theorem (CP vs AP systems)" },
          { id: "p3-dist-consistency", label: "Consistency models (eventual vs strong vs causal)" },
          { id: "p3-dist-partitions", label: "Network partitions are not optional" },
          { id: "p3-dist-fallacies", label: "Fallacies of distributed computing" },
        ],
      },
      {
        id: "p3-kafka",
        title: "Apache Kafka — Architecture & Patterns",
        topics: [
          { id: "p3-kafka-basics", label: "Brokers, topics, partitions, consumer groups, offsets" },
          { id: "p3-kafka-replication", label: "Replication factor" },
          { id: "p3-kafka-producer", label: "Producer semantics (acks=0, acks=1, acks=all)" },
          { id: "p3-kafka-rebalancing", label: "Consumer group rebalancing" },
          { id: "p3-kafka-compaction", label: "Log compaction" },
          { id: "p3-kafka-overkill", label: "When Kafka is overkill vs essential" },
        ],
      },
      {
        id: "p3-event-driven",
        title: "Event-Driven Architecture Patterns",
        topics: [
          { id: "p3-ed-domain-events", label: "Domain events vs integration events" },
          { id: "p3-ed-event-sourcing", label: "Event sourcing concept" },
          { id: "p3-ed-eventual-consistency", label: "Eventual consistency in practice" },
          { id: "p3-ed-saga", label: "Saga pattern (choreography vs orchestration)" },
          { id: "p3-ed-outbox", label: "Outbox pattern for reliable event publishing" },
        ],
      },
      {
        id: "p3-outbox",
        title: "The Outbox Pattern",
        topics: [
          { id: "p3-outbox-problem", label: "The core reliability problem: DB write + event publish" },
          { id: "p3-outbox-2pc", label: "Why distributed transactions (2PC) are dangerous" },
          { id: "p3-outbox-implementation", label: "Outbox table in same DB transaction" },
          { id: "p3-outbox-poller", label: "Separate poller publishes to Kafka" },
          { id: "p3-outbox-exactly-once", label: "Transactional outbox = exactly-once semantics" },
        ],
      },
      {
        id: "p3-websockets",
        title: "WebSockets & Real-Time Systems",
        topics: [
          { id: "p3-ws-protocols", label: "WebSocket vs HTTP long polling vs SSE" },
          { id: "p3-ws-socketio", label: "Socket.io architecture, namespaces, rooms" },
          { id: "p3-ws-scaling", label: "Scaling WebSocket servers (Redis adapter)" },
          { id: "p3-ws-reconnection", label: "Connection management and reconnection strategies" },
        ],
      },
      {
        id: "p3-microservices",
        title: "Microservices — When and Why",
        topics: [
          { id: "p3-ms-monolith", label: "Monolith vs modular monolith vs microservices" },
          { id: "p3-ms-conway", label: "Conway's Law" },
          { id: "p3-ms-hidden-costs", label: "Hidden costs: tracing, auth, latency, ops" },
          { id: "p3-ms-when", label: "When to extract services" },
        ],
      },
      {
        id: "p3-communication",
        title: "Service Communication Patterns",
        topics: [
          { id: "p3-comm-sync", label: "Synchronous (REST, gRPC)" },
          { id: "p3-comm-async", label: "Asynchronous (Kafka, RabbitMQ)" },
          { id: "p3-comm-grpc", label: "gRPC basics: protocol buffers, service definitions" },
          { id: "p3-comm-when-grpc", label: "When to use gRPC vs REST" },
        ],
      },
      {
        id: "p3-horizontal-scaling",
        title: "Horizontal Scaling Fundamentals",
        topics: [
          { id: "p3-hs-stateless", label: "Stateless services (push state to Redis/DB)" },
          { id: "p3-hs-load-balancing", label: "Load balancing algorithms" },
          { id: "p3-hs-sticky-sessions", label: "Sticky sessions and why to avoid them" },
          { id: "p3-hs-blue-green", label: "Blue-green deployment concepts" },
        ],
      },
      {
        id: "p3-idempotency",
        title: "Idempotency & At-Least-Once Delivery",
        topics: [
          { id: "p3-idel-at-least-once", label: "At-least-once delivery guarantee" },
          { id: "p3-idel-idempotent-consumers", label: "Consumers MUST be idempotent" },
          { id: "p3-idel-keys", label: "Idempotency key patterns" },
          { id: "p3-idel-dedup", label: "Deduplication tables" },
          { id: "p3-idel-replay", label: "Design for replay-safety" },
        ],
      },
      {
        id: "p3-circuit-breakers",
        title: "Circuit Breakers & Resilience Patterns",
        topics: [
          { id: "p3-cb-cascading", label: "Why cascading failures happen" },
          { id: "p3-cb-states", label: "Circuit breaker states (closed, open, half-open)" },
          { id: "p3-cb-retry", label: "Retry with exponential backoff and jitter" },
          { id: "p3-cb-timeout", label: "Timeout strategy" },
          { id: "p3-cb-bulkhead", label: "Bulkhead pattern" },
        ],
      },
    ],
    projects: [
      {
        id: "p3-proj-notifications",
        title: "Project 3A — Real-Time Notification System",
        description: "Multi-channel notification platform with Kafka, WebSockets, and delivery guarantees",
        requirements: [
          "Notification types: in-app, email, push (mock), SMS (mock)",
          "Real-time delivery via WebSocket for online users",
          "Fallback to email queue for offline users",
          "User notification preferences (opt-out per type/channel)",
          "Delivery receipts and read tracking",
          "Notification deduplication",
          "Admin endpoint to broadcast to user segments",
        ],
      },
      {
        id: "p3-proj-rideshare",
        title: "Project 3B — Ride-Share Matching Backend",
        description: "Location-based matching with distributed state, geospatial queries, and event coordination",
        requirements: [
          "Driver location updates via WebSocket (every 5 seconds)",
          "Rider requests: find nearest 3 available drivers within 5km",
          "Driver accepts/declines within 30-second timeout",
          "Ride state machine: requested → matched → in-progress → completed",
          "Surge pricing based on supply/demand ratio",
          "Ride events published to Kafka for analytics",
          "Geospatial queries using PostGIS",
        ],
      },
    ],
    checkpoint: [
      "Explain the outbox pattern. Why can't you just wrap a DB write and Kafka publish in a try-catch?",
      "Your Kafka consumer crashes after writing to DB but before committing the offset — what happens?",
      "You have a WebSocket server with 5,000 connections. Deploy a new version with zero dropped connections.",
      "Explain the saga choreography pattern for: place order → reserve inventory → charge payment",
      "When would you NOT use microservices? Give three reasons.",
    ],
  },
  {
    id: "phase-4",
    number: 4,
    title: "Production Engineering",
    subtitle: "Observability, security, CI/CD, SaaS patterns",
    weeks: "Weeks 16–20",
    sections: [
      {
        id: "p4-observability",
        title: "Observability: Metrics, Logs, Traces",
        topics: [
          { id: "p4-obs-pillars", label: "Three pillars of observability" },
          { id: "p4-obs-metrics", label: "Metrics: counters vs gauges vs histograms" },
          { id: "p4-obs-prometheus", label: "Prometheus data model" },
          { id: "p4-obs-alerting", label: "Alerting on SLOs" },
          { id: "p4-obs-logs", label: "Structured JSON logs, log levels, correlation IDs" },
          { id: "p4-obs-tracing", label: "Distributed tracing with OpenTelemetry" },
        ],
      },
      {
        id: "p4-prometheus",
        title: "Prometheus & Grafana",
        topics: [
          { id: "p4-prom-instrument", label: "Instrumenting Node.js with prom-client" },
          { id: "p4-prom-metrics", label: "Request rate, error rate, p50/p99 latency" },
          { id: "p4-prom-queue", label: "Queue depth, cache hit ratio metrics" },
          { id: "p4-prom-promql", label: "PromQL basics" },
          { id: "p4-prom-dashboard", label: "Building a Grafana dashboard" },
        ],
      },
      {
        id: "p4-security",
        title: "Security Hardening",
        topics: [
          { id: "p4-sec-owasp", label: "OWASP Top 10 for APIs" },
          { id: "p4-sec-helmet", label: "Security headers (Helmet.js)" },
          { id: "p4-sec-cors", label: "CORS properly configured" },
          { id: "p4-sec-sqli", label: "SQL injection prevention" },
          { id: "p4-sec-secrets", label: "Secret rotation and management" },
          { id: "p4-sec-deps", label: "Dependency vulnerability scanning" },
        ],
      },
      {
        id: "p4-cicd",
        title: "CI/CD Pipelines",
        topics: [
          { id: "p4-cicd-actions", label: "GitHub Actions workflow" },
          { id: "p4-cicd-stages", label: "Lint → type-check → test → build → deploy" },
          { id: "p4-cicd-branch", label: "Branch protection rules" },
          { id: "p4-cicd-staging", label: "Staging environment mirroring production" },
          { id: "p4-cicd-db-migrations", label: "Database migration in CI" },
          { id: "p4-cicd-rollback", label: "Rollback strategy" },
        ],
      },
      {
        id: "p4-docker",
        title: "Docker & Containerization",
        topics: [
          { id: "p4-docker-multistage", label: "Multi-stage builds" },
          { id: "p4-docker-ignore", label: ".dockerignore" },
          { id: "p4-docker-user", label: "Non-root user" },
          { id: "p4-docker-cache", label: "Layer caching optimization" },
          { id: "p4-docker-healthcheck", label: "Health check instructions" },
          { id: "p4-docker-compose", label: "Docker Compose for local development" },
        ],
      },
      {
        id: "p4-multi-tenancy",
        title: "SaaS Multi-Tenancy Patterns",
        topics: [
          { id: "p4-mt-row-level", label: "Row-level tenancy (shared DB, tenant_id + RLS)" },
          { id: "p4-mt-schema-level", label: "Schema-level tenancy" },
          { id: "p4-mt-db-level", label: "Database-level tenancy" },
          { id: "p4-mt-tradeoffs", label: "Tradeoffs: complexity vs isolation vs cost" },
          { id: "p4-mt-rls", label: "PostgreSQL Row-Level Security" },
          { id: "p4-mt-middleware", label: "Tenant context middleware pattern" },
        ],
      },
      {
        id: "p4-gateway",
        title: "API Gateway & Load Balancing",
        topics: [
          { id: "p4-gw-nginx", label: "Nginx as reverse proxy and load balancer" },
          { id: "p4-gw-health", label: "Health checks" },
          { id: "p4-gw-ssl", label: "SSL termination" },
          { id: "p4-gw-vs-app", label: "Gateway responsibilities vs application responsibilities" },
        ],
      },
      {
        id: "p4-feature-flags",
        title: "Feature Flags & Progressive Rollouts",
        topics: [
          { id: "p4-ff-purpose", label: "Feature flags as production engineering tool" },
          { id: "p4-ff-rollout", label: "Rollout strategies: percentage, segment, kill switch" },
          { id: "p4-ff-dark-launch", label: "Dark launching" },
        ],
      },
      {
        id: "p4-backup",
        title: "Database Backup & Disaster Recovery",
        topics: [
          { id: "p4-backup-wal", label: "PostgreSQL continuous archiving (WAL)" },
          { id: "p4-backup-pitr", label: "Point-in-time recovery" },
          { id: "p4-backup-validation", label: "Backup validation" },
          { id: "p4-backup-rto-rpo", label: "RTO and RPO as business requirements" },
          { id: "p4-backup-read-replicas", label: "Read replicas for reporting" },
        ],
      },
      {
        id: "p4-debugging",
        title: "Production Debugging & Incident Response",
        topics: [
          { id: "p4-debug-logs", label: "Reading production logs during incidents" },
          { id: "p4-debug-traces", label: "Distributed trace for slow request diagnosis" },
          { id: "p4-debug-bottlenecks", label: "Identifying bottlenecks (CPU, memory, DB, network)" },
          { id: "p4-debug-rollback", label: "Rollback decision criteria" },
          { id: "p4-debug-postmortem", label: "Writing a post-mortem: timeline, root cause, action items" },
        ],
      },
    ],
    projects: [
      {
        id: "p4-proj-saas",
        title: "Project 4A — Multi-Tenant SaaS Backend",
        description: "Complete SaaS foundation with billing, RBAC, tenant isolation, and observability",
        requirements: [
          "Tenant onboarding: signup → create tenant → invite team members",
          "Row-level multi-tenancy with PostgreSQL RLS",
          "Subscription tiers: free, pro, enterprise",
          "Usage tracking: API calls per tenant per day",
          "Stripe webhook handling",
          "RBAC: tenant admin, manager, viewer",
          "Full Prometheus instrumentation",
        ],
      },
      {
        id: "p4-proj-analytics",
        title: "Project 4B — Analytics Ingestion Pipeline",
        description: "High-throughput event ingestion with buffering, aggregation, and time-series queries",
        requirements: [
          "Ingest 10,000 events per second via single /track endpoint",
          "Event types: page_view, click, conversion, custom",
          "Batch writing to Kafka to avoid individual INSERTs",
          "Kafka consumer aggregates and bulk inserts into TimescaleDB",
          "Real-time dashboard: events in last 1min, 5min, 1hr",
          "Funnel analysis queries",
          "Data retention: raw 30 days, aggregates 1 year",
        ],
      },
    ],
    checkpoint: [
      "Your service returns 500 errors for 2% of requests. How would you have caught this before users reported it?",
      "A security researcher reports they can view another tenant's data. Walk through every layer. Where did isolation fail?",
      "Your CI/CD deploys a bad migration that drops a column. You notice after 10 minutes. What is your recovery plan?",
      "Explain the difference between RTO and RPO. What do they mean for your backup strategy?",
      "A Stripe webhook for subscription cancellation arrives 3 hours late. How does your system handle this correctly?",
    ],
  },
  {
    id: "phase-5",
    number: 5,
    title: "System Design Mastery",
    subtitle: "Design mastery, capstone project, interviews",
    weeks: "Weeks 21–24",
    sections: [
      {
        id: "p5-framework",
        title: "System Design Frameworks & Methods",
        topics: [
          { id: "p5-fw-reshaded", label: "The RESHADED Framework" },
          { id: "p5-fw-capacity", label: "Capacity estimation (back-of-envelope math)" },
          { id: "p5-fw-consistent-hashing", label: "Consistent hashing" },
          { id: "p5-fw-cqrs", label: "Read Replicas & CQRS" },
          { id: "p5-fw-cdn", label: "CDN Architecture" },
          { id: "p5-fw-sharding", label: "Sharding Strategies" },
          { id: "p5-fw-search", label: "Search Architecture (Elasticsearch/OpenSearch)" },
          { id: "p5-fw-rate-limiting", label: "Rate Limiting at Scale" },
        ],
      },
      {
        id: "p5-design-url-shortener",
        title: "Design: URL Shortener (bit.ly)",
        topics: [
          { id: "p5-url-scale", label: "Scale target: 100M URLs, 10B redirects/month" },
          { id: "p5-url-core", label: "Core components: shortening, redirect, analytics" },
          { id: "p5-url-id", label: "ID generation: auto-increment vs random" },
          { id: "p5-url-cache", label: "Cache-aside with Redis for redirect lookup" },
          { id: "p5-url-bottlenecks", label: "Bottlenecks: write scaling, hot URLs, cache misses" },
        ],
      },
      {
        id: "p5-design-chat",
        title: "Design: Real-Time Chat System (WhatsApp/Slack)",
        topics: [
          { id: "p5-chat-scale", label: "Scale target: 500M users, 100M daily messages" },
          { id: "p5-chat-core", label: "Core: WebSocket gateway, message service, presence, push" },
          { id: "p5-chat-ordering", label: "Message ordering with compound keys" },
          { id: "p5-chat-fanout", label: "Fan-out strategies: write vs read" },
          { id: "p5-chat-large-groups", label: "Large group optimization" },
        ],
      },
      {
        id: "p5-design-notifications",
        title: "Design: Notification System",
        topics: [
          { id: "p5-notif-scale", label: "Scale target: 1B notifications/day" },
          { id: "p5-notif-core", label: "Core: API, priority router, channel dispatchers" },
          { id: "p5-notif-priorities", label: "Priority queues for critical vs marketing" },
          { id: "p5-notif-throttling", label: "Throttling per user" },
          { id: "p5-notif-templates", label: "Centralized template service" },
          { id: "p5-notif-reliability", label: "Retry, DLQ, idempotency patterns" },
        ],
      },
      {
        id: "p5-design-saas",
        title: "Design: SaaS Backend Platform",
        topics: [
          { id: "p5-saas-scale", label: "Scale target: 10K tenants, 1M users/tenant" },
          { id: "p5-saas-core", label: "Core: identity, billing, feature service, gateway" },
          { id: "p5-saas-tenancy-model", label: "Tenancy model decision tree" },
          { id: "p5-saas-noisy-neighbor", label: "Noisy neighbor prevention" },
          { id: "p5-saas-data-residency", label: "Regional data residency" },
        ],
      },
    ],
    projects: [
      {
        id: "p5-capstone",
        title: "Capstone — Distributed Developer Platform",
        description: "Full-stack backend platform combining all phases: auth, real-time, queues, observability, multi-tenancy",
        requirements: [
          "Multi-tenant workspace system (members, RBAC)",
          "Real-time collaborative document updates via WebSocket",
          "Async task processing pipeline with priority queues",
          "Full-text search across workspace content",
          "Event audit log with Kafka",
          "Billing: free / pro / enterprise tiers",
          "Full observability: Prometheus, structured logs, distributed tracing",
          "CI/CD with staging and production environments",
          "API versioning with v1/v2 migration path",
          "Webhook delivery system with retry and signatures",
          "Load test: 1,000 concurrent users with p99 < 200ms",
        ],
      },
    ],
    checkpoint: [
      "Given any system design problem, can you produce a reasonable architecture in 45 minutes?",
      "Can you explain every tradeoff in your design?",
      "What would you do differently with 10x the time or 10x the scale?",
    ],
  },
];
